
<?php  
$title = 'Add User'; 
$this->headTitle($title);  

?> 
<h2><?php echo $this->escapeHtml($title); ?></h2>
<div class="jumbotron">
<?php  
if(!empty($form)) {  
   $form->setAttribute('action', $this->url('user', array('action' => 'add'))); 
   $form->prepare();  
 
   echo $this->form()->openTag($form); 
?>

<?php   
   echo $this->formHidden($form->get('id')); 
   echo $this->formRow($form->get('username'))."<br>"; 
   echo $this->formRow($form->get('password'))."<br><br>"; 
   echo $this->formSubmit($form->get('submit')); 
   echo $this->form()->closeTag(); 
} 
?>
</div>